# This is a basic workflow to help you get started with Actions

name: Add Note To Issue By Label

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types: [ labeled ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  note:
    if: ${{ github.event.label.name == 'dev ready' }} || ${{ github.event.label.name == 'documentation' }}
    runs-on: ubuntu-latest
    steps:
      - name: comment note to ISSUE
        uses: peter-evans/create-or-update-comment@v1.4.4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            #  notes
            
            test
            ...
        
